### ISSUE TITLE
当调用 GuildMessageEvent 后，机器人无法发送消息到QQ群里

### ISSUE THREAD

**Issue by moian98** [mnixry/nonebot-plugin-guild-patch#1]
你好大佬，如题
在频道里使用指令能正常接受机器人的消息，QQ群里使用指令就没有反应了。

**Comment by mnixry** [comment]
根据问题描述, 看起来和这个补丁关系不大

你可以检查一下代码和配置文件设置是否有误

**Comment by moian98** [comment]
代码和配置应该没问题。
我写了一段最简单的测试代码，如图
![IMG_20220225_000054](https://user-images.githubusercontent.com/56097585/155561629-381657ca-9556-491a-9c0e-c78669614328.jpg)

只是一个指令+回复
demo 调用MessageEvent
demo1 调用GuildMessageEvent

下面两张图分别是QQ群截图
![IMG_20220225_000156](https://user-images.githubusercontent.com/56097585/155561831-c004115c-dac5-4e52-9f64-50dac378a870.jpg)

QQ频道截图
![IMG_20220225_000232](https://user-images.githubusercontent.com/56097585/155561917-ed438f88-db51-451a-b749-084b39f5223a.jpg)

还是说我这样调用是错误的吗？
小白请指教，谢谢大佬了。

**Comment by mnixry** [comment]
这是预期行为, 请参考NoneBot2文档的[事件处理函数重载](https://v2.nonebot.dev/docs/advanced/di/overload)一节以了解更多

---

鉴于该issue似乎并不是本项目实际存在的问题, 我将关闭这个issue. 如果有任何问题, 欢迎reopen该issue或者提交一个新的issue.
