### ISSUE TITLE
怎么使用 安装后在频道发消息没反应

### ISSUE THREAD

**Issue by Annnnh1010** [mnixry/nonebot-plugin-guild-patch#13]

**Comment by mnixry** [comment]
请补充更多的有效信息。

**Comment by Annnnh1010** [comment]
![VeryCapture_20230319162250](https://user-images.githubusercontent.com/76246787/226162762-ca4dfdb2-9542-457e-9636-397a82725684.jpg)
![VeryCapture_20230319162305](https://user-images.githubusercontent.com/76246787/226162765-474f33ed-1133-45c4-9569-df3ded61184f.jpg)

**Comment by mnixry** [comment]
GoCQ 那边有收到消息的日志吗

**Comment by Annnnh1010** [comment]
![VeryCapture_20230319162953](https://user-images.githubusercontent.com/76246787/226163003-4d0704fb-1a84-4c2c-93ed-978888588ce7.jpg)
群内可以收到  频道收不到

**Comment by mnixry** [comment]
那么该问题和本插件无关
