### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 1318083885** [mnixry/nonebot-plugin-guild-patch#15]
**请问这个需要在什么系统上运行呢？**

**Comment by 1318083885** [comment]
顺便问一下：我想做一个能把群消息转发到频道的机器人，这个能实现吗？

**Comment by synodriver** [comment]
cpython在哪个系统运行，这个就在哪个系统运行

**Comment by 1318083885** [comment]
> cpython在哪个系统运行，这个就在哪个系统运行

那请问一下，我想做一个能把群消息转发到频道的机器人，这个能实现吗？

**Comment by synodriver** [comment]
都可以实现

**Comment by 1318083885** [comment]
> 都可以实现

谢谢

**Comment by 1318083885** [comment]
> 都可以实现

可以带带吗
